In [143]:
import numpy as np

In [152]:
N = 6
a = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        a[i, j] = 3. / (0.6*i*j + 1)

np.linalg.matrix_rank(a)


6

In [145]:
def diy_lu(a):
    """Создает LU - разложение матрицы `a`.
    
    Наивное LU - разложение: работает столбец за столбцом, накапливает элементарные треугольные матрицы.
    Без выбора главного элемента.
    """
    N = a.shape[0]
        
    a, finish_replace = test_matrix(a,N)

    u = a.copy()
    L = np.eye(N)
    for j in range(N-1):
        lam = np.eye(N)
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u

        lam[j+1:, j] = gamma
        L = L @ lam
    return L, u, finish_replace

In [157]:
def test_matrix(matrixA, N, count=0):
    #replace - массив всевозможных замен столбцов. replace[0]=[0,0] Для удобтва.
    replace = []
    replace.append([0,0])
    for s1 in range(N-1):
        for s2 in range(s1+1,N):
            replace.append([s1,s2])
            
            
    # Меняем местами столбец под номером replace[count][0] 
    # со столбцом под номером replace[count][1]      
    matrixA = replace_j(matrixA, N, replace[count][0], replace[count][1])
    
    for k in range(1,N+1):
        
        b = np.zeros((k, k), dtype=float)
        for i in range(k):
            for j in range(k):
                b[i,j] = matrixA[i,j]
        
        if np.sqrt(np.linalg.det(b)**2) < 10**-15:
            matrixA_old = replace_j(matrixA, N, replace[count][1], replace[count][0])
            return test_matrix(matrixA_old, N, count + 1)
        
    return matrixA, replace[count]
    

In [147]:
np.set_printoptions(precision=3)


In [137]:
L, u, fin_rep = diy_lu(a)

print(L, "\n")
print(u, "\n")

LU = replace_j(L@u, a.shape[0], fin_rep[1], fin_rep[0])

print(LU, end='\n\n\n')

print(L@u, end='\n\n\n')

# Быстрый тест на адекватность: L @ U должна быть равна изначальной матрице с точностью до ошибок округления.
print(L@u - a)

[[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    1.455 1.    0.    0.    0.   ]
 [1.    1.714 1.742 1.    0.    0.   ]
 [1.    1.882 2.276 2.039 1.    0.   ]
 [1.    2.    2.671 2.944 2.354 1.   ]] 

[[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -1.125e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  2.625e-01  4.574e-01  5.975e-01  7.013e-01]
 [ 0.000e+00  2.220e-16  0.000e+00 -2.197e-02 -4.480e-02 -6.469e-02]
 [ 0.000e+00 -4.528e-16  0.000e+00  6.939e-18  8.080e-04  1.902e-03]
 [ 0.000e+00  4.123e-16  0.000e+00 -1.634e-17  0.000e+00 -1.585e-05]] 

[[3.    3.    3.    3.    3.    3.   ]
 [3.    1.875 1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]]


[[3.    3.    3.    3.    3.    3.   ]
 [3.    1.875 1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517

In [172]:
a1 = a.copy()
a1[1, 1] = 3

In [173]:
print(a1, "\n\n\n")

L, u, fin_rep = diy_lu(a1)

print(L, "\n")
print(u, "\n")


print(L@u, end='\n\n\n')
LU = replace_j(L@u, a.shape[0], fin_rep[1], fin_rep[0])
print(fin_rep)
print(LU, end='\n\n\n')

# Быстрый тест на адекватность: L @ U должна быть равна изначальной матрице с точностью до ошибок округления.
print(L@u - a1, end='\n\n\n')


[[3.    3.    3.    3.    3.    3.   ]
 [3.    3.    1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]] 



[[1.    0.    0.    0.    0.    0.   ]
 [0.455 1.    0.    0.    0.    0.   ]
 [0.294 0.294 1.    0.    0.    0.   ]
 [0.217 0.256 1.179 1.    0.    0.   ]
 [0.172 0.223 1.294 1.635 1.    0.   ]
 [0.143 0.196 1.375 2.07  2.082 1.   ]] 

[[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00  1.636e+00  1.636e+00 -2.922e-01 -4.813e-01 -6.136e-01]
 [ 0.000e+00 -5.551e-17  1.636e+00 -1.442e-01 -2.236e-01 -2.733e-01]
 [ 0.000e+00  6.542e-17  0.000e+00  6.143e-02  1.005e-01  1.272e-01]
 [ 0.000e+00 -3.515e-17  0.000e+00  0.000e+00 -1.830e-03 -3.810e-03]
 [ 0.000e+00  1.412e-17  0.000e+00  0.000e+00  0.000e+00  2.567e-05]] 

[[3.    3.    3.    3.    3.    3.   ]
 [1.364 3.    3.    1.071 0.882 0.75 ]
 [0.882 1.364 3.    0.652 0.5

In [108]:
def replace_j(a,N,j1,j2):
    for i in range(N):
        a[i,j1], a[i,j2] = a[i,j2], a[i,j1]
    return a