In [1]:
import numpy as np
import matplotlib.pyplot as plt


A = np.matrix([[3,1,0,0], 
               [1,2,0,1], 
               [0,0,1,1], 
               [0,1,1,1]])

n = len(A)
v = np.random.random(n)

v /= np.sqrt(v @ v)

In [2]:
for i in range(100):
    v = np.array(v @ A)
    v /= np.sqrt(v.dot(v.T))
print(v)

[[0.77250966 0.58000058 0.08832178 0.2429556 ]]


In [3]:
print((v @ A) / v)
print((np.sum((v @ A) / v) / len(v[0])).round(2))

[[3.75080042 3.75080042 3.75080042 3.75080042]]
3.75


In [4]:
A = np.matrix([[3,1,0,0], 
               [1,2,0,1], 
               [0,0,1,1], 
               [0,1,1,1]])
result_error = 10**-3
n = len(A)

v = np.random.random(n)
v /= np.sqrt(v @ v)

sys = np.linalg.eigh(A)
real_v = np.array(sys[1][:,3].T)

sign = np.sign(v[0]/real_v[0,0])
v = np.matrix(sign * v).T

error = np.linalg.norm(v - real_v)
print('Start error', error)

i = 0
while error > result_error:
    i += 1
    v = np.array(A @ v)
    v /= np.linalg.norm(v)
    error = np.linalg.norm(v.T - real_v)
    print('iteration', i, 'error =', error)
print(v.T)
print(real_v)

Start error 1.6726969953861202
iteration 1 error = 0.33531763341768467
iteration 2 error = 0.2016652202635066
iteration 3 error = 0.12446644704276104
iteration 4 error = 0.07698162604323916
iteration 5 error = 0.04761018952223069
iteration 6 error = 0.029437753507415794
iteration 7 error = 0.0181986917192437
iteration 8 error = 0.011249714130792893
iteration 9 error = 0.006953886855639922
iteration 10 error = 0.004298405359974311
iteration 11 error = 0.002656956956613431
iteration 12 error = 0.001642330776551687
iteration 13 error = 0.0010151642981371346
iteration 14 error = 0.0006274973281461688
[[-0.77218753 -0.58021989 -0.08861902 -0.24334744]]
[[-0.77250966 -0.58000058 -0.08832178 -0.2429556 ]]


In [5]:
Q_max = np.sum((A @ v) / v) / n
print((A @ v) / v)
print(Q_max.round(2))

[[3.75139764]
 [3.75025881]
 [3.74599549]
 [3.74849375]]
3.75


In [6]:
A = np.matrix([[3,1,0,0], 
               [1,2,0,1], 
               [0,0,1,1], 
               [0,1,1,1]])
result_error = 10**-3
m = 3.5
n = len(A)

v = np.random.random(n)
v /= np.sqrt(v @ v)

sys = np.linalg.eigh(A)
real_v = np.array(sys[1][:,3].T)

sign = np.sign(v[0]/real_v[0,0])
v = np.matrix(sign * v).T

error = np.linalg.norm(v - real_v)
print('Start error', error)

i = 0
while error > result_error:
    i += 1
    v = np.linalg.inv(A - m * np.eye(n)) @ v
    v /= np.linalg.norm(v)
    error = np.linalg.norm(v.T - real_v)
    print('iteration', i, 'error =', error)
print(v.T)
print(real_v)

Start error 1.4583524885289072
iteration 1 error = 0.31915723498854587
iteration 2 error = 0.06746103325826448
iteration 3 error = 0.014176162429170927
iteration 4 error = 0.0029998183269321333
iteration 5 error = 0.0006362200723888927
[[-0.77283019 -0.5797882  -0.08801006 -0.2425559 ]]
[[-0.77250966 -0.58000058 -0.08832178 -0.2429556 ]]


In [7]:
A = np.matrix([[3,1,0,0], 
               [1,2,0,1], 
               [0,0,1,1], 
               [0,1,1,1]])
result_error = 10**-3
m = 3.7
n = len(A)

v = np.random.random(n)
v /= np.sqrt(v @ v)

sys = np.linalg.eigh(A)
real_v = np.array(sys[1][:,3].T)

sign = np.sign(v[0]/real_v[0,0])
v = np.matrix(sign * v).T

error = np.linalg.norm(v - real_v)
print('Start error', error)

i = 0
while error > result_error:
    i += 1
    v = np.linalg.solve(A - m * np.eye(n), v)
    v /= np.linalg.norm(v)
    error = np.linalg.norm(v.T - real_v)
    print('iteration', i, 'error =', error)
print(v.T)
print(real_v)

Start error 1.3350369402356808
iteration 1 error = 0.036944167176248
iteration 2 error = 0.001287282546899639
iteration 3 error = 4.655088852815998e-05
[[-0.77253129 -0.57998824 -0.08829657 -0.24292542]]
[[-0.77250966 -0.58000058 -0.08832178 -0.2429556 ]]
