Задачи с одной звёздой. Задачи под номерами 20 23 отсутствуют.

Всего задач 33 - 2(нерешённые) = 31

Баллы 31 * 1.5 = 46.5

1 Import the numpy package under the name np

In [2]:
import numpy as np

2 Print the numpy version and the configuration

In [7]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


3 Create a null vector of size 10 

In [8]:
V = np.zeros(10)
print(V)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4 How to find the memory size of any array

In [12]:
M = np.zeros((10,10))
print(M.size)
print(M.itemsize)
print(M.size * M.itemsize, 'байт')

100
8
800 байт


5 How to get the documentation of the numpy add function from the command line?

в командной строке написать
python -c "import numpy; numpy.info(numpy.add)"

6 Create a null vector of size 10 but the fifth value which is 1

In [14]:
V = np.zeros(10)
V[4] = 1
print(V)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7 Create a vector with values ranging from 10 to 49

In [15]:
V = np.arange(10,50)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8 Reverse a vector (first element becomes last) 

In [18]:
V = np.arange(10)
print(V)
V = V[::-1]
print(V)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


9 Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
M = np.arange(0, 9).reshape(3,3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10 Find indices of non-zero elements from [1,2,0,0,4,0]

In [28]:
V = np.nonzero([1,2,0,0,4,0])
print(V[0])

[0 1 4]


11 Create a 3x3 identity matrix

In [34]:
M = np.eye(3)
print(M)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12 Create a 3x3x3 array with random values

In [35]:
M3 = np.random.random((3,3,3))
print(M3)

[[[0.9027958  0.65820664 0.33894195]
  [0.06858739 0.66270194 0.80354785]
  [0.7064125  0.88081408 0.19211283]]

 [[0.94824196 0.7682615  0.99657537]
  [0.57370214 0.03963261 0.77225338]
  [0.7685065  0.38224923 0.47844211]]

 [[0.7975747  0.66580258 0.93626608]
  [0.5111956  0.98383035 0.94654893]
  [0.28758025 0.04623295 0.47439487]]]


13 Create a 10x10 array with random values and find the minimum and maximum values

In [37]:
M = np.random.random((10,10))
Mmin, Mmax = M.min(), M.max()
print(Mmin, Mmax)

0.019198234867426223 0.9947924118904888


14 Create a random vector of size 30 and find the mean value

In [10]:
V = np.random.random(30)
m = V.mean()
print(m)

0.5050495486047635


15 Create a 2d array with 1 on the border and 0 inside 

In [42]:
M = np.ones((8,8))
M[1:-1,1:-1] = 0
print(M)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


16 How to add a border (filled with 0’s) around an existing array?

In [44]:
M = np.ones((5,15))
M = np.pad(M, pad_width=1, mode='constant', constant_values=0)
print(Z, len(M), len(M[0]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 7 17


17 What is the result of the following expression? 

In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [149]:
M = np.diag(np.arange(1,5), -1)
print(M)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [53]:
M = np.zeros((8,8), dtype=int)
M[1::2,::2] = 1
M[::2,1::2] = 1
print(M)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


21. Create a checkerboard 8x8 matrix using the tile function

In [55]:
M = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(M)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix

In [83]:
M = np.random.random((5,5))
M2 = (M - np.mean (M)) / (np.std (M))
print(M2)

[[-1.04479871 -0.99657895  0.39082309 -0.63277926 -0.82708155]
 [ 1.13184241 -0.94174366 -0.64512226  0.70995434  0.41801474]
 [-1.1540395   1.15680109  0.54294153  0.34968543  1.43102806]
 [-1.16125835  1.79977339  0.07651023  0.63437422 -0.76153879]
 [-1.4731312  -0.25570011  0.95303445  1.6521263  -1.35313696]]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [87]:
M = np.dot(np.ones((5,3)), np.ones((3,2)))

print(M)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [89]:
M = np.arange(11)
M[(3 < M) & (M < 8)] *= -1
print(M)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


26. What is the output of the following script?

In [94]:
print(sum(range(5),-1)) 
from numpy import *
print(sum(range(5),-1)) 

10
10


27. Consider an integer vector Z, which of these expressions are legal?

In [102]:
M = np.arange(11)
print(M)

#Z**Z no
print(2 << M >> 2)
print(M <- M)
print(1j*M)
print(M/1/1)
#Z<Z>Z no

[ 0  1  2  3  4  5  6  7  8  9 10]
[  0   1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


28. What are the result of the following expressions?

In [117]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-2.14748365e+09]


<ipython-input-117-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-117-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


29. How to round away from zero a float array ?

In [120]:
M = np.random.uniform(-10,+10,10)
print(M)
print(np.copysign(np.ceil(np.abs(M)),M))

[-5.23566716  5.63192955 -6.84849327 -1.65567135 -1.47685696 -0.40415069
 -5.99198065  1.86436189  6.82185334  6.03744463]
[-6.  6. -7. -2. -2. -1. -6.  2.  7.  7.]


30. How to find common values between two arrays?

In [132]:
m1 = np.random.randint(0,10,10)
m2 = np.random.randint(0,10,10)
print(m1)
print(m2)
print(np.intersect1d(m1,m2))

[1 1 6 7 1 6 1 9 6 2]
[5 2 8 3 4 1 2 9 1 5]
[1 2 9]


31. How to ignore all numpy warnings (not recommended)?

In [137]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print('hello world',Z)

hello world [inf]


32. Is the following expressions true? 

In [140]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

False
nan
1j


33. How to get the dates of yesterday, today and tomorrow?

In [144]:
ys = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
td = np.datetime64('today', 'D')
tm = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(ys, td, tm)

2020-10-12 2020-10-13 2020-10-14
